#!/bin/bash

# Do not edit this file directly. It is set by the function col_sw()
SET_FULL_PROMPT="no"
SET_THEME_VAR="125"
SET_BARCOL="\[\033[0;1;34m\]"
SET_TXTCOL="\[\033[1;1;35m\]"
SET_PATHCOL_VAR="1"
SET_PATHCOL="\[\033[0;37m\]"
